version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - blit
  - CDKEY
  - Cherno
  - DGRAM
  - ebooklib
  - elif
  - Pixmap
  - println
  - seriies
  - wangmingdong
  - Zhang
  - zhangpenghua
ignoreWords: []
import: []
